apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: follow-semver02
  namespace: argocd
  annotations:
    #argocd-image-updater.argoproj.io/image-list: ghcr.io/codefresh-contrib/gitops-cert-level-2-examples:~1
    argocd-image-updater.argoproj.io/image-list: ghcr.io/sbrodriguez/codefresh-at-scale:~1
spec:
  project: default

  source:
    #repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
    repoURL: https://github.com/sbrodriguez/codefresh-at-scale.git
    targetRevision: HEAD
    #path: ./image-updater/example-app/envs/staging/
    path: ./orig/image-updater/example-app/envs/staging/
   
  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
